name: repository_dispatch working
on:
  pull_request:
    types: opened
    branches:
      - jira
  repository_dispatch:
    event-type : [event-triggered-by-jira]
 # pull_request:

jobs:
  Jira_approval:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Java Script Action
        id: greet #assigning an ID to this step
        uses: actions/hello-world-javascript-action@v1 #This action prints "Hello World" or "Hello" + the name of a person to greet to the log. Refer to https://github.com/actions/hello-world-javascript-action
        with:
          who-to-greet: Chai-Var #Input:Required The name of the person to greet. Default "World"
      - name: Log greeting time
        run: echo "${{steps.greet.outputs.time}}" #called the first step using its ID and printing The time we greeted you i.e the time the first step got executed.
